# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["mccurdyc22@gmail.com"]
description = "Apply performance, security and usability upgrades to static bucket services such as Google Cloud Storage or AWS S3."
language = "rust"
manifest_version = 2
name = "wasm.mccurdyc.dev"
service_id = ""

[setup]

  [setup.backends]

    [setup.backends.bucket_origin]
      address = "mock-s3.edgecompute.app"
      port = 443
